spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:init_data.sql

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 3600000
    refresh: 2592000000

apiPrefix: /api/v1
